- name: Pull Docker Registry image
  community.docker.docker_image:
    name: registry
    source: pull

- name: Create directory for registry config.yml
  file:
    path: /etc/docker/registry/
    state: directory

- name: Configure registry config.yml
  copy:
    dest: /etc/docker/registry/config.yml
    content: |
      proxy:
        remoteurl: https://registry-1.docker.io

- name: Create docker registry container
  community.docker.docker_container:
    name: registry
    image: registry
    detach: true
    recreate: true
    restart_policy: unless-stopped
    mounts:
    - type: bind
      source: /etc/docker/registry/
      target: /etc/registry/
    ports:
      - 5000:5000
    state: started

- name: Update daemon.json
  copy:
    dest: /etc/docker/daemon.json
    content: |
      {
        "registry-mirrors": ["http://localhost:5000"]
      }

- name: Restart docker daemon
  systemd:
    name: docker
    state: restarted

